CREATE SCHEMA IF NOT EXISTS svc_auth;

CREATE TABLE IF NOT EXISTS svc_auth.users (
  id UUID PRIMARY KEY,
  email TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
